export interface Emoticon {
  id: string;
  value: string;
  meaning?: string;
  tags?: string[];
}

const emoticonsMetadata: Omit<Emoticon, 'id'>[] = [
  {
    value: ':‑)',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: ':)',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: ':-]',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: ':]',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: ':->',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: ':>',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: '8-)',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: '8)',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: ':-}',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: ':}',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: ':^)',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: '=]',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: '=)',
    meaning: 'Smiley, happy face',
    tags: ['smiley', 'happy', 'face'],
  },
  {
    value: ':‑D',
    meaning: 'Laughing, big grin, grinning with glasses',
    tags: ['laughing', 'big', 'grin', 'grinning', 'with', 'glasses'],
  },
  {
    value: ':D',
    meaning: 'Laughing, big grin, grinning with glasses',
    tags: ['laughing', 'big', 'grin', 'grinning', 'with', 'glasses'],
  },
  {
    value: '8‑D',
    meaning: 'Laughing, big grin, grinning with glasses',
    tags: ['laughing', 'big', 'grin', 'grinning', 'with', 'glasses'],
  },
  {
    value: '8D',
    meaning: 'Laughing, big grin, grinning with glasses',
    tags: ['laughing', 'big', 'grin', 'grinning', 'with', 'glasses'],
  },
  {
    value: '=D',
    meaning: 'Laughing, big grin, grinning with glasses',
    tags: ['laughing', 'big', 'grin', 'grinning', 'with', 'glasses'],
  },
  {
    value: '=3',
    meaning: 'Laughing, big grin, grinning with glasses',
    tags: ['laughing', 'big', 'grin', 'grinning', 'with', 'glasses'],
  },
  {
    value: 'B^D',
    meaning: 'Laughing, big grin, grinning with glasses',
    tags: ['laughing', 'big', 'grin', 'grinning', 'with', 'glasses'],
  },
  {
    value: 'c:',
    meaning: 'Laughing, big grin, grinning with glasses',
    tags: ['laughing', 'big', 'grin', 'grinning', 'with', 'glasses'],
  },
  {
    value: 'C:',
    meaning: 'Laughing, big grin, grinning with glasses',
    tags: ['laughing', 'big', 'grin', 'grinning', 'with', 'glasses'],
  },
  {
    value: 'x‑D',
    meaning: 'Laughing',
    tags: ['laughing'],
  },
  {
    value: 'X‑D',
    meaning: 'Laughing',
    tags: ['laughing'],
  },
  {
    value: ':-))',
    meaning: 'Very happy or double chin',
    tags: ['very', 'happy', 'double', 'chin'],
  },
  {
    value: ':))',
    meaning: 'Very happy or double chin',
    tags: ['very', 'happy', 'double', 'chin'],
  },
  {
    value: ':‑(',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ':(',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ':‑c',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ':c',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ':‑<',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ':<',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ':‑[',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ':[',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ':-||',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ':{',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ':@',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ';(',
    meaning: 'Frown, sad, pouting',
    tags: ['frown', 'sad', 'pouting'],
  },
  {
    value: ":'‑(",
    meaning: 'Crying',
    tags: ['crying'],
  },
  {
    value: ":'(",
    meaning: 'Crying',
    tags: ['crying'],
  },
  {
    value: ':=(',
    meaning: 'Crying',
    tags: ['crying'],
  },
  {
    value: ":'‑)",
    meaning: 'Tears of happiness',
    tags: ['tears', 'happiness'],
  },
  {
    value: ":')",
    meaning: 'Tears of happiness',
    tags: ['tears', 'happiness'],
  },
  {
    value: ':"D',
    meaning: 'Tears of happiness',
    tags: ['tears', 'happiness'],
  },
  {
    value: '>:(',
    meaning: 'Angry',
    tags: ['angry'],
  },
  {
    value: '>:[',
    meaning: 'Angry',
    tags: ['angry'],
  },
  {
    value: "D‑':",
    meaning: 'Horror, disgust, sadness, great dismay (right to left)',
    tags: ['horror', 'disgust', 'sadness', 'great', 'dismay', 'right', 'left'],
  },
  {
    value: 'D:<',
    meaning: 'Horror, disgust, sadness, great dismay (right to left)',
    tags: ['horror', 'disgust', 'sadness', 'great', 'dismay', 'right', 'left'],
  },
  {
    value: 'D:',
    meaning: 'Horror, disgust, sadness, great dismay (right to left)',
    tags: ['horror', 'disgust', 'sadness', 'great', 'dismay', 'right', 'left'],
  },
  {
    value: 'D8',
    meaning: 'Horror, disgust, sadness, great dismay (right to left)',
    tags: ['horror', 'disgust', 'sadness', 'great', 'dismay', 'right', 'left'],
  },
  {
    value: 'D;',
    meaning: 'Horror, disgust, sadness, great dismay (right to left)',
    tags: ['horror', 'disgust', 'sadness', 'great', 'dismay', 'right', 'left'],
  },
  {
    value: 'D=',
    meaning: 'Horror, disgust, sadness, great dismay (right to left)',
    tags: ['horror', 'disgust', 'sadness', 'great', 'dismay', 'right', 'left'],
  },
  {
    value: ':‑O',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: ':O',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: ':‑o',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: ':o',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: ':-0',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: ':0',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: '8‑0',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: '>:O',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: '=O',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: '=o',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: '=0',
    meaning: 'Surprise, shock',
    tags: ['surprise', 'shock'],
  },
  {
    value: ':-3',
    meaning: 'Cat face, curled mouth, cutesy, playful, mischievous',
    tags: [
      'cat',
      'face',
      'curled',
      'mouth',
      'cutesy',
      'playful',
      'mischievous',
    ],
  },
  {
    value: ':3',
    meaning: 'Cat face, curled mouth, cutesy, playful, mischievous',
    tags: [
      'cat',
      'face',
      'curled',
      'mouth',
      'cutesy',
      'playful',
      'mischievous',
    ],
  },
  {
    value: 'x3',
    meaning: 'Cat face, curled mouth, cutesy, playful, mischievous',
    tags: [
      'cat',
      'face',
      'curled',
      'mouth',
      'cutesy',
      'playful',
      'mischievous',
    ],
  },
  {
    value: 'X3',
    meaning: 'Cat face, curled mouth, cutesy, playful, mischievous',
    tags: [
      'cat',
      'face',
      'curled',
      'mouth',
      'cutesy',
      'playful',
      'mischievous',
    ],
  },
  {
    value: '>:3',
    meaning: 'Lion smile, evil cat, playfulness',
    tags: ['lion', 'smile', 'evil', 'cat', 'playfulness'],
  },
  {
    value: ':-*',
    meaning: 'Kiss',
    tags: ['kiss'],
  },
  {
    value: ':*',
    meaning: 'Kiss',
    tags: ['kiss'],
  },
  {
    value: ':x',
    meaning: 'Kiss',
    tags: ['kiss'],
  },
  {
    value: ';‑)',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: ';)',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: '*-)',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: '*)',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: ';‑]',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: ';]',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: ';^)',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: ';>',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: ':‑,',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: ';D',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: ';3',
    meaning: 'Wink, smirk',
    tags: ['wink', 'smirk'],
  },
  {
    value: ':‑P',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: ':P',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: 'X‑P',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: 'x‑p',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: ':‑p',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: ':p',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: ':‑Þ',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: ':Þ',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: ':‑þ',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: ':þ',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: ':‑b',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: ':b',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: 'd:',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: '=p',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: '>:b',
    meaning: 'Tongue sticking out, cheeky/playful, blowing a raspberry',
    tags: [
      'tongue',
      'sticking',
      'out',
      'cheeky',
      'playful',
      'blowing',
      'raspberry',
    ],
  },
  {
    value: ':-/',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: ':/',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: "',:^I",
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: '>:\\',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: '>:/',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: ':\\',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: '=/',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: '=\\',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: ':L',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: '=L',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: ':S',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: ':‑|',
    meaning: 'Straight face no expression, indecision',
    tags: ['straight', 'face', 'expression', 'indecision'],
  },
  {
    value: ':|',
    meaning: 'Straight face no expression, indecision',
    tags: ['straight', 'face', 'expression', 'indecision'],
  },
  {
    value: ':$',
    meaning: 'Embarrassed, blushing',
    tags: ['embarrassed', 'blushing'],
  },
  {
    value: '://)',
    meaning: 'Embarrassed, blushing',
    tags: ['embarrassed', 'blushing'],
  },
  {
    value: '://3',
    meaning: 'Embarrassed, blushing',
    tags: ['embarrassed', 'blushing'],
  },
  {
    value: ':‑X',
    meaning: 'Sealed lips, wearing braces, tongue-tied',
    tags: ['sealed', 'lips', 'wearing', 'braces', 'tongue', 'tied'],
  },
  {
    value: ':X',
    meaning: 'Sealed lips, wearing braces, tongue-tied',
    tags: ['sealed', 'lips', 'wearing', 'braces', 'tongue', 'tied'],
  },
  {
    value: ':‑#',
    meaning: 'Sealed lips, wearing braces, tongue-tied',
    tags: ['sealed', 'lips', 'wearing', 'braces', 'tongue', 'tied'],
  },
  {
    value: ':#',
    meaning: 'Sealed lips, wearing braces, tongue-tied',
    tags: ['sealed', 'lips', 'wearing', 'braces', 'tongue', 'tied'],
  },
  {
    value: ':‑&',
    meaning: 'Sealed lips, wearing braces, tongue-tied',
    tags: ['sealed', 'lips', 'wearing', 'braces', 'tongue', 'tied'],
  },
  {
    value: ':&',
    meaning: 'Sealed lips, wearing braces, tongue-tied',
    tags: ['sealed', 'lips', 'wearing', 'braces', 'tongue', 'tied'],
  },
  {
    value: 'O:‑)',
    meaning: 'Angel, halo, saint, innocent',
    tags: ['angel', 'halo', 'saint', 'innocent'],
  },
  {
    value: 'O:)',
    meaning: 'Angel, halo, saint, innocent',
    tags: ['angel', 'halo', 'saint', 'innocent'],
  },
  {
    value: '0:‑3',
    meaning: 'Angel, halo, saint, innocent',
    tags: ['angel', 'halo', 'saint', 'innocent'],
  },
  {
    value: '0:3',
    meaning: 'Angel, halo, saint, innocent',
    tags: ['angel', 'halo', 'saint', 'innocent'],
  },
  {
    value: '0:‑)',
    meaning: 'Angel, halo, saint, innocent',
    tags: ['angel', 'halo', 'saint', 'innocent'],
  },
  {
    value: '0:)',
    meaning: 'Angel, halo, saint, innocent',
    tags: ['angel', 'halo', 'saint', 'innocent'],
  },
  {
    value: '0;^)',
    meaning: 'Angel, halo, saint, innocent',
    tags: ['angel', 'halo', 'saint', 'innocent'],
  },
  {
    value: '>:‑)',
    meaning: 'Evil, devilish',
    tags: ['evil', 'devilish'],
  },
  {
    value: '>:)',
    meaning: 'Evil, devilish',
    tags: ['evil', 'devilish'],
  },
  {
    value: '}:‑)',
    meaning: 'Evil, devilish',
    tags: ['evil', 'devilish'],
  },
  {
    value: '}:)',
    meaning: 'Evil, devilish',
    tags: ['evil', 'devilish'],
  },
  {
    value: '3:‑)',
    meaning: 'Evil, devilish',
    tags: ['evil', 'devilish'],
  },
  {
    value: '3:)',
    meaning: 'Evil, devilish',
    tags: ['evil', 'devilish'],
  },
  {
    value: '>;‑)',
    meaning: 'Evil, devilish',
    tags: ['evil', 'devilish'],
  },
  {
    value: '>;)',
    meaning: 'Evil, devilish',
    tags: ['evil', 'devilish'],
  },
  {
    value: '>;3',
    meaning: 'Evil, devilish',
    tags: ['evil', 'devilish'],
  },
  {
    value: '|;‑)',
    meaning: 'Cool, bored, yawning',
    tags: ['cool', 'bored', 'yawning'],
  },
  {
    value: '|‑O',
    meaning: 'Cool, bored, yawning',
    tags: ['cool', 'bored', 'yawning'],
  },
  {
    value: 'B-)',
    meaning: 'Cool, bored, yawning',
    tags: ['cool', 'bored', 'yawning'],
  },
  {
    value: ':‑J',
    meaning: 'Tongue-in-cheek',
    tags: ['tongue', 'cheek'],
  },
  {
    value: '#‑)',
    meaning: 'Partied all night',
    tags: ['partied', 'all', 'night'],
  },
  {
    value: '%‑)',
    meaning: 'Drunk, confused',
    tags: ['drunk', 'confused'],
  },
  {
    value: '%)',
    meaning: 'Drunk, confused',
    tags: ['drunk', 'confused'],
  },
  {
    value: ':‑###..',
    meaning: 'Being sick',
    tags: ['being', 'sick'],
  },
  {
    value: ':###..',
    meaning: 'Being sick',
    tags: ['being', 'sick'],
  },
  {
    value: '<:‑|',
    meaning: 'Dumb, dunce-like',
    tags: ['dumb', 'dunce', 'like'],
  },
  {
    value: "',:-|",
    meaning: 'Scepticism, disbelief, disapproval',
    tags: ['scepticism', 'disbelief', 'disapproval'],
  },
  {
    value: "',:-l",
    meaning: 'Scepticism, disbelief, disapproval',
    tags: ['scepticism', 'disbelief', 'disapproval'],
  },
  {
    value: ':E',
    meaning: 'Grimacing, nervous, awkward',
    tags: ['grimacing', 'nervous', 'awkward'],
  },
  {
    value: '8-X',
    meaning: 'Skull and crossbones',
    tags: ['skull', 'and', 'crossbones'],
  },
  {
    value: '8=X',
    meaning: 'Skull and crossbones',
    tags: ['skull', 'and', 'crossbones'],
  },
  {
    value: 'x-3',
    meaning: 'Skull and crossbones',
    tags: ['skull', 'and', 'crossbones'],
  },
  {
    value: 'x=3',
    meaning: 'Skull and crossbones',
    tags: ['skull', 'and', 'crossbones'],
  },
  {
    value: '~:>',
    meaning: 'Chicken',
    tags: ['chicken'],
  },
  {
    value: '@};-',
    meaning: 'Rose',
    tags: ['rose'],
  },
  {
    value: '@}->--',
    meaning: 'Rose',
    tags: ['rose'],
  },
  {
    value: "@}‑;‑'‑‑‑",
    meaning: 'Rose',
    tags: ['rose'],
  },
  {
    value: '@>‑‑>‑‑',
    meaning: 'Rose',
    tags: ['rose'],
  },
  {
    value: '8====D',
    meaning: 'Penis, Ejaculation',
    tags: ['penis', 'ejaculation'],
  },
  {
    value: '8===D',
    meaning: 'Penis, Ejaculation',
    tags: ['penis', 'ejaculation'],
  },
  {
    value: '8=D',
    meaning: 'Penis, Ejaculation',
    tags: ['penis', 'ejaculation'],
  },
  {
    value: '3=D',
    meaning: 'Penis, Ejaculation',
    tags: ['penis', 'ejaculation'],
  },
  {
    value: '8=>',
    meaning: 'Penis, Ejaculation',
    tags: ['penis', 'ejaculation'],
  },
  {
    value: '8===D~~~',
    meaning: 'Penis, Ejaculation',
    tags: ['penis', 'ejaculation'],
  },
  {
    value: '*<|:‑)',
    meaning: 'Santa Claus',
    tags: ['santa', 'claus'],
  },
  {
    value: '</3',
    meaning: 'Broken heart',
    tags: ['broken', 'heart'],
  },
  {
    value: '<\\3',
    meaning: 'Broken heart',
    tags: ['broken', 'heart'],
  },
  {
    value: '<3',
    meaning: 'Heart',
    tags: ['heart'],
  },
  {
    value: 's2',
    meaning: 'Heart',
    tags: ['heart'],
  },
  {
    value: '><>',
    meaning: "Fish, something's fishy, Ichthys",
    tags: ['fish', 'something', 'fishy', 'ichthys'],
  },
  {
    value: '<><',
    meaning: "Fish, something's fishy, Ichthys",
    tags: ['fish', 'something', 'fishy', 'ichthys'],
  },
  {
    value: '<*)))‑{',
    meaning: "Fish, something's fishy, Ichthys",
    tags: ['fish', 'something', 'fishy', 'ichthys'],
  },
  {
    value: '><(((*>',
    meaning: "Fish, something's fishy, Ichthys",
    tags: ['fish', 'something', 'fishy', 'ichthys'],
  },
  {
    value: 'o/',
    meaning: 'Waving hello, or half of high-five ',
    tags: ['waving', 'hello', 'half', 'high', 'five'],
  },
  {
    value: '\\o',
    meaning: 'Waving hello, or half of high-five ',
    tags: ['waving', 'hello', 'half', 'high', 'five'],
  },
  {
    value: '\\o/',
    meaning: 'Cheer "Yay, yay."',
    tags: ['cheer', 'yay'],
  },
  {
    value: '*\\0/*',
    meaning: 'Cheerleader',
    tags: ['cheerleader'],
  },
  {
    value: 'o7',
    meaning: 'Salute',
    tags: ['salute'],
  },
  {
    value: 'v.v',
    meaning: 'Sadness, great dismay, disgust',
    tags: ['sadness', 'great', 'dismay', 'disgust'],
  },
  {
    value: '._.',
    meaning: 'Sadness, great dismay, disgust',
    tags: ['sadness', 'great', 'dismay', 'disgust'],
  },
  {
    value: '._.;',
    meaning: 'Sadness, great dismay, disgust',
    tags: ['sadness', 'great', 'dismay', 'disgust'],
  },
  {
    value: ';-;',
    meaning: 'Crying',
    tags: ['crying'],
  },
  {
    value: 'T_T',
    meaning: 'Crying',
    tags: ['crying'],
  },
  {
    value: 'T-T',
    meaning: 'Crying',
    tags: ['crying'],
  },
  {
    value: 'X_X',
    meaning: 'Dead person, fainted',
    tags: ['dead', 'person', 'fainted'],
  },
  {
    value: 'x_x',
    meaning: 'Dead person, fainted',
    tags: ['dead', 'person', 'fainted'],
  },
  {
    value: '+_+',
    meaning: 'Dead person, fainted',
    tags: ['dead', 'person', 'fainted'],
  },
  {
    value: 'X_x',
    meaning: 'Dead person, fainted',
    tags: ['dead', 'person', 'fainted'],
  },
  {
    value: 'x_X',
    meaning: 'Dead person, fainted',
    tags: ['dead', 'person', 'fainted'],
  },
  {
    value: '<_<',
    meaning: 'Sideways look, devious or guilty[citation needed]',
    tags: ['sideways', 'look', 'devious', 'guilty', 'citation', 'needed'],
  },
  {
    value: '>_>',
    meaning: 'Sideways look, devious or guilty[citation needed]',
    tags: ['sideways', 'look', 'devious', 'guilty', 'citation', 'needed'],
  },
  {
    value: '<.<',
    meaning: 'Sideways look, devious or guilty[citation needed]',
    tags: ['sideways', 'look', 'devious', 'guilty', 'citation', 'needed'],
  },
  {
    value: '>.>',
    meaning: 'Sideways look, devious or guilty[citation needed]',
    tags: ['sideways', 'look', 'devious', 'guilty', 'citation', 'needed'],
  },
  {
    value: 'O_O',
    meaning: 'Surprise, shock, yawn',
    tags: ['surprise', 'shock', 'yawn'],
  },
  {
    value: 'o_o',
    meaning: 'Surprise, shock, yawn',
    tags: ['surprise', 'shock', 'yawn'],
  },
  {
    value: 'O-O',
    meaning: 'Surprise, shock, yawn',
    tags: ['surprise', 'shock', 'yawn'],
  },
  {
    value: 'o‑o',
    meaning: 'Surprise, shock, yawn',
    tags: ['surprise', 'shock', 'yawn'],
  },
  {
    value: 'O_o',
    meaning: 'Surprise, shock, yawn',
    tags: ['surprise', 'shock', 'yawn'],
  },
  {
    value: 'o_O',
    meaning: 'Surprise, shock, yawn',
    tags: ['surprise', 'shock', 'yawn'],
  },
  {
    value: '>.<',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: '>_<',
    meaning: 'Skeptical, annoyed, undecided, uneasy, hesitant',
    tags: ['skeptical', 'annoyed', 'undecided', 'uneasy', 'hesitant'],
  },
  {
    value: '^5',
    meaning: 'High five',
    tags: ['high', 'five'],
  },
  {
    value: 'o/\\o',
    meaning: 'High five',
    tags: ['high', 'five'],
  },
  {
    value: '>_>^ ^<_<',
    meaning: 'High five',
    tags: ['high', 'five'],
  },
  {
    value: 'V.v.V',
    meaning: 'Crab, lobster',
    tags: ['crab', 'lobster'],
  },
  {
    value: 'V=(° °)=V',
    meaning: 'Crab, lobster',
    tags: ['crab', 'lobster'],
  },
  {
    value: '(^^^)',
    meaning: 'Shark',
    tags: ['shark'],
  },
  {
    value: '(::[]::)',
    meaning: 'Bandage',
    tags: ['bandage'],
  },
  {
    value: '(o)(o)',
    meaning: 'Breasts',
    tags: ['breasts'],
  },
  {
    value: '( • )( • )',
    meaning: 'Breasts',
    tags: ['breasts'],
  },
  {
    value: '(. Y .)',
    meaning: 'Breasts',
    tags: ['breasts'],
  },
  {
    value: 'ӽd̲̅a̲̅r̲̅w̲̅i̲̅ɳ̲̅ᕗ',
    meaning: 'Darwin fish, evolution fish',
    tags: ['darwin', 'fish', 'evolution', 'fish'],
  },
  {
    value: 'Ӽd̲̅a̲̅r̲̅w̲̅i̲̅ɳ̲̅ᕗ',
    meaning: 'Darwin fish, evolution fish',
    tags: ['darwin', 'fish', 'evolution', 'fish'],
  },
  {
    value: '[̲̅$̲̅(̲̅1̲̅)̲̅$̲̅]',
    meaning: 'Dollar notes',
    tags: ['dollar', 'notes'],
  },
  {
    value: '[̲̅$̲̅(̲̅5̲̅)̲̅$̲̅]',
    meaning: 'Dollar notes',
    tags: ['dollar', 'notes'],
  },
  {
    value: '[̲̅$̲̅(̲̅1̲̅0̲̅)̲̅$̲̅]',
    meaning: 'Dollar notes',
    tags: ['dollar', 'notes'],
  },
  {
    value: '[̲̅$̲̅(̲̅ιοο̲̅)̲̅$̲̅]',
    meaning: 'Dollar notes',
    tags: ['dollar', 'notes'],
  },
  {
    value: '( ͡° ͜ʖ ͡°)',
    meaning:
      'The "Lenny Face", named and popularized on 4chan. Used mostly to suggest mischief, imply sexual innuendo or a second hidden meaning behind a sentence, or is pasted over and over to spam online discussions.',
    tags: [
      'the',
      'lenny',
      'face',
      'named',
      'and',
      'popularized',
      'chan',
      'used',
      'mostly',
      'suggest',
      'mischief',
      'imply',
      'sexual',
      'innuendo',
      'second',
      'hidden',
      'meaning',
      'behind',
      'sentence',
      'pasted',
      'over',
      'and',
      'over',
      'spam',
      'online',
      'discussions',
    ],
  },
  {
    value: 'ヽ༼ຈل͜ຈ༽ﾉ',
    meaning:
      '"Raise Your Dongers", a meme originated from Twitch, unclear meaning',
    tags: [
      'raise',
      'your',
      'dongers',
      'meme',
      'originated',
      'from',
      'twitch',
      'unclear',
      'meaning',
    ],
  },
  {
    value: 'ಠ_ಠ',
    meaning: '"Look of Disapproval"',
    tags: ['look', 'disapproval'],
  },
  {
    value: 'ಠ__ಠ',
    meaning: '"Look of Disapproval"',
    tags: ['look', 'disapproval'],
  },
  {
    value: 'ಠ益ಠ',
    meaning: '"Look of Disapproval"',
    tags: ['look', 'disapproval'],
  },
  {
    value: '⎛⎝(•ⱅ•)⎠⎞',
    meaning: 'Bat',
    tags: ['bat'],
  },
  {
    value: '◥▅◤',
    meaning: 'Bat',
    tags: ['bat'],
  },
  {
    value: '◢▅◣',
    meaning: 'Bat',
    tags: ['bat'],
  },
  {
    value: '(๑ˇεˇ๑)',
    meaning: 'Kiss',
    tags: ['kiss'],
  },
  {
    value: '( ༎ຶ ۝ ༎ຶ )',
    meaning: 'Crying',
    tags: ['crying'],
  },
  {
    value: '(=ʘᆽʘ=)∫',
    meaning: 'Cat',
    tags: ['cat'],
  },
  {
    value: 'ฅ(^•ﻌ•^ฅ)',
    meaning: 'Cat',
    tags: ['cat'],
  },
  {
    value: 'ʕ •ᴥ•ʔ',
    meaning: 'Bear',
    tags: ['bear'],
  },
  {
    value: 'ʕ ·(エ)· ʔ',
    meaning: 'Bear',
    tags: ['bear'],
  },
  {
    value: 'ʕ – ㉨ – ʔ',
    meaning: 'Bear',
    tags: ['bear'],
  },
  {
    value: '⊂(￣(ｴ)￣)⊃',
    meaning: 'Bear',
    tags: ['bear'],
  },
  {
    value: '(>_<)(>_<)>(>w<)',
    meaning: 'Troubled',
    tags: ['troubled'],
  },
  {
    value: "(';')",
    meaning: 'Baby',
    tags: ['baby'],
  },
  {
    value: '(^^ゞ(^_^;)(-_-;)(~_~;)',
    meaning: 'Nervous, embarrassed, troubled, shy, sweat drop',
    tags: ['nervous', 'embarrassed', 'troubled', 'shy', 'sweat', 'drop'],
  },
  {
    value: '(・.・;)(・_・;)(・・;)',
    meaning: 'Nervous, embarrassed, troubled, shy, sweat drop',
    tags: ['nervous', 'embarrassed', 'troubled', 'shy', 'sweat', 'drop'],
  },
  {
    value: '^^;^_^;(#^.^#)(^^;)',
    meaning: 'Nervous, embarrassed, troubled, shy, sweat drop',
    tags: ['nervous', 'embarrassed', 'troubled', 'shy', 'sweat', 'drop'],
  },
  {
    value: '(⁄ ⁄•⁄ω⁄•⁄ ⁄)',
    meaning: 'Embarrassed, flushed',
    tags: ['embarrassed', 'flushed'],
  },
  {
    value: '(^.^)y-.o○(-.-)y-°°°',
    meaning: 'Smoking',
    tags: ['smoking'],
  },
  {
    value: '(-_-)zzz',
    meaning: 'Sleeping',
    tags: ['sleeping'],
  },
  {
    value: '((+_+))(+o+)(°°)(°-°)',
    meaning: 'Confused',
    tags: ['confused'],
  },
  {
    value: '(°.°)(°_°)(°_°>)(°レ°)',
    meaning: 'Confused',
    tags: ['confused'],
  },
  {
    value: '(o|o)',
    meaning: 'Ultraman',
    tags: ['ultraman'],
  },
  {
    value: '<(｀^´)>',
    meaning:
      '—.mw-parser-output .sr-only{border:0;clip:rect(0,0,0,0);clip-path:polygon(0px 0px,0px 0px,0px 0px);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px;white-space:nowrap}N/a',
    tags: [
      'parser',
      'output',
      'only',
      'border',
      'clip',
      'rect',
      'clip',
      'path',
      'polygon',
      'height',
      'margin',
      'overflow',
      'hidden',
      'padding',
      'position',
      'absolute',
      'width',
      'white',
      'space',
      'nowrap',
    ],
  },
  {
    value: '<m(__)m>m(__)mm(_ _)m',
    meaning: 'Kowtow as a sign of respect, or dogeza for apology',
    tags: ['kowtow', 'sign', 'respect', 'dogeza', 'for', 'apology'],
  },
  {
    value: '(凸ಠ益ಠ)凸',
    meaning: 'Middle fingers',
    tags: ['middle', 'fingers'],
  },
  {
    value: '＼(°ロ＼)(／ロ°)／',
    meaning: 'Questioning',
    tags: ['questioning'],
  },
  {
    value: ';_;;-;;n;;;',
    meaning: 'Sad, crying',
    tags: ['sad', 'crying'],
  },
  {
    value: 'Q.QT.TTnTQQQ_Q',
    meaning: 'Sad, crying',
    tags: ['sad', 'crying'],
  },
  {
    value: '(=_=)',
    meaning: 'Tired',
    tags: ['tired'],
  },
  {
    value: '(=^・^=)(=^・・^=)=^_^=',
    meaning: 'Cat',
    tags: ['cat'],
  },
  {
    value: '(..)(._.)',
    meaning: 'Looking down in sadness or boredom',
    tags: ['looking', 'down', 'sadness', 'boredom'],
  },
  {
    value: '^m^',
    meaning: 'Giggling with hand covering mouth',
    tags: ['giggling', 'with', 'hand', 'covering', 'mouth'],
  },
  {
    value: '(・・?(?_?)',
    meaning: 'Confusion',
    tags: ['confusion'],
  },
  {
    value: '(－‸ლ)',
    meaning: 'Facepalm',
    tags: ['facepalm'],
  },
  {
    value: '＼(~o~)／＼(^o^)／＼(-o-)／',
    meaning: 'Excited',
    tags: ['excited'],
  },
  {
    value: 'ヽ(^。^)ノヽ(^o^)丿(*^0^*)',
    meaning: 'Excited',
    tags: ['excited'],
  },
  {
    value: '(*_*)(*_*;(+_+)',
    meaning: 'Amazed',
    tags: ['amazed'],
  },
  {
    value: '(@_@)(@_@。(＠_＠;)＼(◎o◎)／！',
    meaning: 'Amazed',
    tags: ['amazed'],
  },
  {
    value: '!(^^)!',
    meaning: '—N/a',
    tags: [],
  },
  {
    value: '(*^^)v(^^)v(^_^)v（’-’*)',
    meaning: 'Laughing, cheerful',
    tags: ['laughing', 'cheerful'],
  },
  {
    value: '＼(^o^)／\\(^o^)/',
    meaning: 'Hopeless',
    tags: ['hopeless'],
  },
  {
    value: '(~o~)(~_~)',
    meaning: '—N/a',
    tags: [],
  },
  {
    value: '(^^ゞ',
    meaning: '—N/a',
    tags: [],
  },
  {
    value: 'ˊ＿>ˋ',
    meaning: 'Calmness',
    tags: ['calmness'],
  },
  {
    value: '(p_-)(-_q)',
    meaning: '—N/a',
    tags: [],
  },
  {
    value: '((d[-_-]b))',
    meaning: 'Headphones, listening to music',
    tags: ['headphones', 'listening', 'music'],
  },
  {
    value: '(・へ・)(｀´)<`～´><`ヘ´>(ーー;)',
    meaning: 'Worried',
    tags: ['worried'],
  },
  {
    value: '(^0_0^)',
    meaning: 'Eyeglasses',
    tags: ['eyeglasses'],
  },
  {
    value: '( ..)φφ(..)',
    meaning: 'Jotting note',
    tags: ['jotting', 'note'],
  },
  {
    value: '(●＾o＾●)(＾ｖ＾)(＾ｕ＾)(＾◇＾)',
    meaning: 'Happy',
    tags: ['happy'],
  },
  {
    value: '(￣ー￣)',
    meaning: 'Grinning',
    tags: ['grinning'],
  },
  {
    value: '(*´▽｀*)(*°∀°)=3',
    meaning: 'Infatuation',
    tags: ['infatuation'],
  },
  {
    value: 'ᕕ( ᐛ )ᕗ',
    meaning: 'Dancing, swinging arms back and forth, "Happy Gary"',
    tags: [
      'dancing',
      'swinging',
      'arms',
      'back',
      'and',
      'forth',
      'happy',
      'gary',
    ],
  },
  {
    value: '（ ﾟ Дﾟ)(°◇°)',
    meaning: 'Shocked, surprised',
    tags: ['shocked', 'surprised'],
  },
  {
    value: '(*￣m￣)',
    meaning: 'Dissatisfied',
    tags: ['dissatisfied'],
  },
  {
    value: '(´･ω･`)(‘A`)',
    meaning: 'Snubbed or deflated',
    tags: ['snubbed', 'deflated'],
  },
  {
    value: '(づ￣ ³￣)づ',
    meaning: 'Hugging/reaching and kissing',
    tags: ['hugging', 'reaching', 'and', 'kissing'],
  },
  {
    value: '.....φ(・∀・＊)',
    meaning: 'Studying',
    tags: ['studying'],
  },
  {
    value: '囧',
    meaning:
      'Distress. Jiong, a Chinese character meaning a "patterned window", now repurposed as an ideographic emoticon.',
    tags: [
      'distress',
      'jiong',
      'chinese',
      'character',
      'meaning',
      'patterned',
      'window',
      'now',
      'repurposed',
      'ideographic',
      'emoticon',
    ],
  },
  {
    value: '.o○○o.',
    meaning: 'Bubbles',
    tags: ['bubbles'],
  },
  {
    value: '( ^^)_U~~( ^^)_旦~~',
    meaning: 'Cup of tea',
    tags: ['cup', 'tea'],
  },
  {
    value: '<+))><<<*))>=<',
    meaning: 'Fish',
    tags: ['fish'],
  },
  {
    value: '<コ:彡 Ｃ:.ミ',
    meaning: 'Squid, octopus',
    tags: ['squid', 'octopus'],
  },
  {
    value: '~>°)～～～',
    meaning: 'Snake',
    tags: ['snake'],
  },
  {
    value: '～°·_·°～',
    meaning: 'Bat',
    tags: ['bat'],
  },
  {
    value: '(°°)～',
    meaning: 'Tadpole',
    tags: ['tadpole'],
  },
  {
    value: '●～*',
    meaning: 'Bomb',
    tags: ['bomb'],
  },
  {
    value: '￣|○STOOTZOTLorz囧rz',
    meaning:
      'Despair. The "O"s represent head on the ground, "T" or "r" forms the torso, and "S" or "z" the legs.',
    tags: [
      'despair',
      'the',
      'represent',
      'head',
      'the',
      'ground',
      'forms',
      'the',
      'torso',
      'and',
      'the',
      'legs',
    ],
  },
  {
    value: '(╯°□°)╯︵ ┻━┻┬──┬ ¯\\_(ツ)',
    meaning: 'Table flip',
    tags: ['table', 'flip'],
  },
  {
    value: '(ノಠ益ಠ)ノ彡┻━┻',
    meaning: 'Table flip',
    tags: ['table', 'flip'],
  },
  {
    value: '|:3ミ',
    meaning: '—N/a',
    tags: [],
  },
  {
    value: 'm(_ _)m',
    meaning: 'Kowtow as a sign of respect, or dogeza for apology',
    tags: ['kowtow', 'sign', 'respect', 'dogeza', 'for', 'apology'],
  },
  {
    value: '(´･ω･`)',
    meaning: 'Snubbed or deflated',
    tags: ['snubbed', 'deflated'],
  },
  {
    value: '(`･ω･´)',
    meaning: 'Feel perky',
    tags: ['feel', 'perky'],
  },
  {
    value: '(｀-´)>',
    meaning: 'Salute',
    tags: ['salute'],
  },
  {
    value: '(´；ω；`)',
    meaning: 'Terribly sad',
    tags: ['terribly', 'sad'],
  },
  {
    value: 'ヽ(´ー｀)ﾉ',
    meaning: 'Peace of mind',
    tags: ['peace', 'mind'],
  },
  {
    value: 'ヽ(`Д´)ﾉ',
    meaning: 'Be irritable',
    tags: ['irritable'],
  },
  {
    value: '(＃ﾟДﾟ)',
    meaning: 'Angry',
    tags: ['angry'],
  },
  {
    value: '（ ´Д｀）',
    meaning: 'Yelling, or panting',
    tags: ['yelling', 'panting'],
  },
  {
    value: '（　ﾟДﾟ）',
    meaning: 'Surprised, or loudmouthed',
    tags: ['surprised', 'loudmouthed'],
  },
  {
    value: "┐('～`；)┌",
    meaning: "Don't know the answer",
    tags: ['don', 'know', 'the', 'answer'],
  },
  {
    value: '（´∀｀）',
    meaning: 'Carefree',
    tags: ['carefree'],
  },
  {
    value: '（　´_ゝ`）',
    meaning: 'Indifferent',
    tags: ['indifferent'],
  },
  {
    value: 'Σ(゜д゜;)',
    meaning: 'Shocked',
    tags: ['shocked'],
  },
  {
    value: '( ﾟヮﾟ)',
    meaning: 'Happy, upbeat',
    tags: ['happy', 'upbeat'],
  },
  {
    value: '⊂二二二（＾ω＾）二⊃',
    meaning:
      '"Bu-n", being carefree and above, with arms stretched out while running/soaring',
    tags: [
      'being',
      'carefree',
      'and',
      'above',
      'with',
      'arms',
      'stretched',
      'out',
      'while',
      'running',
      'soaring',
    ],
  },
  {
    value: '(((( ；ﾟДﾟ)))',
    meaning: 'Spook',
    tags: ['spook'],
  },
  {
    value: 'Σ(ﾟДﾟ)',
    meaning: 'Huge surprise',
    tags: ['huge', 'surprise'],
  },
  {
    value: '( ´∀｀)σ)∀`)',
    meaning: "Jog (poke) someone's cheek",
    tags: ['jog', 'poke', 'someone', 'cheek'],
  },
  {
    value: '( ﾟдﾟ)',
    meaning: 'Amazed',
    tags: ['amazed'],
  },
  {
    value: '(´ー`)y-~~',
    meaning: 'Smoking',
    tags: ['smoking'],
  },
  {
    value: '（ ^_^）o自自o（^_^ ）',
    meaning: 'Toast "Cheers"',
    tags: ['toast', 'cheers'],
  },
  {
    value: 'm9(・∀・)',
    meaning: 'Flash of intuition',
    tags: ['flash', 'intuition'],
  },
  {
    value: 'ヽ(´ー`)人(´∇｀)人(`Д´)ノ',
    meaning: 'Friendly',
    tags: ['friendly'],
  },
  {
    value: "('A`)",
    meaning: 'Lonely',
    tags: ['lonely'],
  },
  {
    value: '（ ´,_ゝ`)',
    meaning: 'Depressed, unsatisfied (based on indifferent)',
    tags: ['depressed', 'unsatisfied', 'based', 'indifferent'],
  },
  {
    value: '（´-`）.｡oO( ... )',
    meaning: 'Thinking',
    tags: ['thinking'],
  },
  {
    value: '(ﾟДﾟ;≡;ﾟДﾟ)',
    meaning: 'Impatience',
    tags: ['impatience'],
  },
  {
    value: '( ´д)ﾋｿ(´Д｀)ﾋｿ(Д｀)',
    meaning: 'Whispers',
    tags: ['whispers'],
  },
  {
    value: '（･∀･)つ⑩',
    meaning: 'Carrying money',
    tags: ['carrying', 'money'],
  },
  {
    value: '⊂（ﾟДﾟ⊂⌒｀つ≡≡≡(´⌒;;;≡≡≡',
    meaning: 'Sliding on belly, "whooaaa!!!"',
    tags: ['sliding', 'belly', 'whooaaa'],
  },
  {
    value: '(ﾟдﾟ)',
    meaning: 'Unforeseen',
    tags: ['unforeseen'],
  },
  {
    value: '(ﾟ⊿ﾟ)',
    meaning: '"I don\'t need it"',
    tags: ['don', 'need'],
  },
  {
    value: 'щ(ﾟДﾟщ)',
    meaning: 'Come on',
    tags: ['come'],
  },
  {
    value: '(屮ﾟДﾟ)屮',
    meaning: 'Come on',
    tags: ['come'],
  },
  {
    value: '（・∀・）',
    meaning: 'Mocking, "good"',
    tags: ['mocking', 'good'],
  },
  {
    value: '（・Ａ・）',
    meaning: '"That\'s bad"',
    tags: ['that', 'bad'],
  },
  {
    value: '(ﾟ∀ﾟ)',
    meaning: 'Discharged drug-in-brain, goofing around, "A-HYA!"',
    tags: ['discharged', 'drug', 'brain', 'goofing', 'around', 'hya'],
  },
  {
    value: '（つ Д ｀）',
    meaning: 'Sad',
    tags: ['sad'],
  },
  {
    value: 'エェェ(´д｀)ェェエ',
    meaning: 'Not convincing',
    tags: ['not', 'convincing'],
  },
  {
    value: '[ﾟдﾟ]',
    meaning: 'Deflagged',
    tags: ['deflagged'],
  },
  {
    value: 'd(*⌒▽⌒*)b',
    meaning: 'Happy expression',
    tags: ['happy', 'expression'],
  },
  {
    value: '＿￣',
    meaning:
      'Given up. Despair. The "O"s represent head on the ground, "T" or "r" forms the torso, and "S" or "z" the legs.',
    tags: [
      'given',
      'despair',
      'the',
      'represent',
      'head',
      'the',
      'ground',
      'forms',
      'the',
      'torso',
      'and',
      'the',
      'legs',
    ],
  },
  {
    value: '(╬ ಠ益ಠ)',
    meaning: 'Extreme Distaste, meant to appear as an exaggerated grimace',
    tags: ['extreme', 'distaste', 'meant', 'appear', 'exaggerated', 'grimace'],
  },
  {
    value: '(≧ロ≦)',
    meaning: 'Shouting',
    tags: ['shouting'],
  },
  {
    value: '(ΘεΘ;)',
    meaning: 'Pretending not to notice, asleep because of boredom',
    tags: ['pretending', 'not', 'notice', 'asleep', 'because', 'boredom'],
  },
  {
    value: '＼ ￣ヘ￣',
    meaning: 'Kick',
    tags: ['kick'],
  },
  {
    value: '┌(；`～,)┐',
    meaning: 'Discombobulated',
    tags: ['discombobulated'],
  },
  {
    value: 'ε=ε=ε=┌(;*´Д`)ﾉ',
    meaning: 'Running',
    tags: ['running'],
  },
  {
    value: 'ヽ(´▽`)/',
    meaning: 'Happy',
    tags: ['happy'],
  },
  {
    value: '^ㅂ^',
    meaning: 'Happy',
    tags: ['happy'],
  },
  {
    value: "(l'o'l)",
    meaning: 'Shocked',
    tags: ['shocked'],
  },
  {
    value: 'ヽ(o`皿′o)ﾉ',
    meaning: 'Really angry',
    tags: ['really', 'angry'],
  },
  {
    value: 'キタ━━━(゜∀゜)━━━!!!!!',
    meaning:
      '"It\'s here", Kitaa!, excitement that something has appeared or happened or "I came".',
    tags: [
      'here',
      'kitaa',
      'excitement',
      'that',
      'something',
      'has',
      'appeared',
      'happened',
      'came',
    ],
  },
  {
    value: '(*´Д`)ﾊｧﾊｧ',
    meaning: 'Erotic stirring, haa haa',
    tags: ['erotic', 'stirring', 'haa', 'haa'],
  },
  {
    value: '(　´Д｀)ﾉ(´･ω･`)　ﾅﾃﾞﾅﾃﾞ',
    meaning: 'Patting, nade nade',
    tags: ['patting', 'nade', 'nade'],
  },
  {
    value: '（・∀・ ）ヾ(- -；)コラコラ',
    meaning: 'Blaming "now now"',
    tags: ['blaming', 'now', 'now'],
  },
  {
    value: '0',
    meaning: 'F',
    tags: [],
  },
  {
    value: '1',
    meaning: 'F',
    tags: [],
  },
  {
    value: '2',
    meaning: 'F',
    tags: [],
  },
  {
    value: '3',
    meaning: 'F',
    tags: [],
  },
  {
    value: '4',
    meaning: 'F',
    tags: [],
  },
  {
    value: '5',
    meaning: 'F',
    tags: [],
  },
  {
    value: '6',
    meaning: 'F',
    tags: [],
  },
  {
    value: '7',
    meaning: 'F',
    tags: [],
  },
  {
    value: '8',
    meaning: 'F',
    tags: [],
  },
  {
    value: '9',
    meaning: 'F',
    tags: [],
  },
  {
    value: '( .-. )',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '( .o.)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '( `·´ )',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '( ° ͜ ʖ °)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '( ︶︿︶)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(\\/)(°,,,°)(\\/)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(¬_¬)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(¬º-°)¬',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(¬‿¬)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(´・ω・)っ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ó ì_í)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: "(ʘᗩʘ')",
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ʘ‿ʘ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(͡° ͜ʖ ͡°)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ಠ_ಠ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ಠ‿ಠ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ಠ⌣ಠ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ಥ_ಥ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ಥ﹏ಥ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ง ͠° ͟ل͜ ͡°)ง',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ง ͡ʘ ͜ʖ ͡ʘ)ง',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ง •̀_•́)ง',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: "(ง'̀-'́)ง",
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ง°ل͜°)ง',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ง⌐□ل͜□)ง',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ღ˘⌣˘ღ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ᵔᴥᵔ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(•ω•)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(•◡•)/',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(⊙ω⊙)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(⌐■_■)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(─‿‿─)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(╯°□°）╯',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(◕‿◕)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(っ◕‿◕)っ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(づ｡◕‿‿◕｡)づ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ノಠ益ಠ)ノ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ノ・∀・)ノ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(；一_一)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(｀◔ ω ◔´)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(｡◕‿‿◕｡)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ﾉ◕ヮ◕)ﾉ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '*<{:¬{D}}}',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '=^.^=',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 't(-.-t)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '| (• ◡•)|',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '~(˘▾˘~)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '¬_¬',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '¯(°_o)/¯',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '¯\\_(ツ)_/¯',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '°Д°',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ɳ༼ຈل͜ຈ༽ɲ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ʅʕ•ᴥ•ʔʃ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ʕ´•ᴥ•`ʔ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ʕ•ᴥ•ʔ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ʕ◉.◉ʔ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ʕㅇ호ㅇʔ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ʕ；•`ᴥ•´ʔ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ʘ‿ʘ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '͡° ͜ʖ ͡°',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ζ༼Ɵ͆ل͜Ɵ͆༽ᶘ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'Ѱζ༼ᴼل͜ᴼ༽ᶘѰ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ب_ب',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '٩◔̯◔۶',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ಠoಠ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ಠ~ಠ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ಠ‿ಠ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ಠ⌣ಠ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ಠ╭╮ಠ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ರ_ರ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ง ͠° ل͜ °)ง',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '๏̯͡๏﴿',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '༼ ºººººل͟ººººº ༽',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '༼ ºل͟º ༽',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '༼ ºل͟º༼',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '༼ ºل͟º༽',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '༼ ͡■ل͜ ͡■༽',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '༼ つ ◕_◕ ༽つ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '༼ʘ̚ل͜ʘ̚༽',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ლ(´ڡ`ლ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ლ(́◉◞౪◟◉‵ლ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ლ(ಠ益ಠლ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ᄽὁȍ ̪őὀᄿ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ᔑ•ﺪ͟͠•ᔐ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ᕙ(⇀‸↼‶)ᕗ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ᕙ༼ຈل͜ຈ༽ᕗ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ᶘ ᵒᴥᵒᶅ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ﾉಥ益ಥ）ﾉ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '⊙▃⊙',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '⊙﹏⊙',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '┌( ಠ_ಠ)┘',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '╚(ಠ_ಠ)=┐',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '◉_◉',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '◔ ⌣ ◔',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '◔̯◔',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '◕‿↼',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '◕‿◕',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '〆(・∀・＠)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ノ( º _ ºノ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ノ( ゜-゜ノ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ヽ( ͝° ͜ʖ͡°)ﾉ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ヽ༼° ͟ل͜ ͡°༽ﾉ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ヽ༼ʘ̚ل͜ʘ̚༽ﾉ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ヽ༼ຈل͜ຈ༽ง',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ヽ༼Ὸل͜ຈ༽ﾉ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ヾ(⌐■_■)ノ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '꒰･◡･๑꒱',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '﴾͡๏̯͡๏﴿',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '｡◕‿◕｡',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ʕノ◔ϖ◔ʔノ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '꒰•̥̥̥̥̥̥̥ ﹏ •̥̥̥̥̥̥̥̥๑꒱',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ಠ_ರೃ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ू˃̣̣̣̣̣̣︿˂̣̣̣̣̣̣ ू)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ꈨຶꎁꈨຶ)۶”',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ꐦ°᷄д°᷅)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(۶ૈ ۜ ᵒ̌▱๋ᵒ̌ )۶ૈ=͟͟͞͞ ⌨',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '₍˄·͈༝·͈˄₎◞ ̑̑ෆ⃛',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '٩꒰･ัε･ั ꒱۶',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ヘ（。□°）ヘ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '˓˓(ृ　 ु ॑꒳’)ु(ृ’꒳ ॑ ृ　)ु˒˒˒',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '૮( ᵒ̌ૢཪᵒ̌ૢ )ა',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '“ψ(｀∇´)ψ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ಠﭛಠ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(๑>ᴗ<๑)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(۶ꈨຶꎁꈨຶ )۶ʸᵉᵃʰᵎ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(oT-T)尸',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ಥ‿ಥ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ॱ॰⋆(˶ॢ‾᷄﹃‾᷅˵ॢ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '┬┴┬┴┤  (ಠ├┬┴┬┴',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'Σ (੭ु ຶਊ ຶ)੭ु⁾⁾',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(⑅ ॣ•͈ᴗ•͈ ॣ)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: 'ヾ(´￢｀)ﾉ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(•̀o•́)ง',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(๑•॒̀ ູ॒•́๑)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '=͟͟͞͞ =͟͟͞͞ ﾍ( ´Д`)ﾉ',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(((╹д╹;)))',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '(ᵒ̤̑ ₀̑ ᵒ̤̑)',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
  {
    value: '\\_(ʘ_ʘ)_/',
    meaning: 'Cool ascii face',
    tags: ['face', 'cool'],
  },
];

export const emoticons: Emoticon[] = emoticonsMetadata.map(
  (metadata, index) => ({
    id: `emo-${index}`,
    ...metadata,
  }),
);
